Checking seq

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,39 +1,56 @@
-name: Testing Cascading Steps
-on: push
+name: Push to main
+on:
+  push:
+    branches:
+      - main
+
 
 jobs:
-  job-one:
+
+  clone-and-run-unit-tests:
     runs-on: ubuntu-latest
-    name: "Job 1"
+    name: Clone and run Unit-Tests
     steps:
+      - run: echo "Clone and run unit tests"
+      - run: exit 1
 
 
-      # Step 1
-      - name: Step 1
-        run: echo "ok"
-
-      # Step 2
-      - name: Step 2
-        id: step-2
-        run: echo ""
-
-      # Step 3
-      - name: Step 3
-        id: step-3
-        run: exit 1
-
-      # Step 3 fail
-      - name: Step 3 Error Han
-        if: failure() && steps.step-3.outcome == 'failure'
-        run: echo "${{ toJSON(steps) }}"
+  unit-tests-failed:
+    needs: clone-and-run-unit-tests
+    if: failure() && needs.clone-and-run-unit-tests.result == 'failure'
+    runs-on: ubuntu-latest
+    name: Unit tests failed
+    steps:
+      - run: echo "Unit tests failed"
 
 
+  build-binary-and-run-system-tests:
+    needs: clone-and-run-unit-tests
+    runs-on: ubuntu-latest
+    name: Build binary and run System Tests
+    steps:
+      - run: echo "Building and running system tests"
 
-      # Step 4
-      - name: Step 4
-        run: echo "ok"
+  system-tests-failed:
+    needs: build-binary-and-run-system-tests
+    if: failure() && needs.build-binary-and-run-system-tests.result == 'failure'
+    runs-on: ubuntu-latest
+    name: System tests failed
+    steps:
+      - run: echo "System tests failed"
 
 
-      # Step 5
-      - name: Step 5
-        run: echo "ok"
+  build-docker-image-and-push-to-docker-hub:
+    needs: build-binary-and-run-system-tests
+    runs-on: ubuntu-latest
+    name: Build Docker image and push to Dockerhub
+    steps:
+      - run: echo "Building Docker image and push to Dockerhub"
+
+
+  cleanup-job:
+    runs-on: ubuntu-latest
+    name: Cleanup
+    needs: build-docker-image-and-push-to-docker-hub
+    steps:
+      - run: echo ""
