.

diff --git a/.github/workflows/push_to_master.yaml b/.github/workflows/push_to_master.yaml
--- a/.github/workflows/push_to_master.yaml
+++ b/.github/workflows/push_to_master.yaml
@@ -27,8 +27,7 @@ jobs:
     needs: job-one
     steps:
 
-      # Checkout code
-      - uses: actions/checkout@v4
+      - run: exit 1
 
       - name: Step 1
         run: echo "Running Step 1"
@@ -36,6 +35,14 @@ jobs:
       # Step 2
       - name: Step 2
         run: echo "Running Step 2"
+
+
+  job-two-error-handler:
+    runs-on: ubuntu-latest
+    needs: job-two
+    steps:
+      - run: echo " Job 2 failed "
+
 
   # JOB 3
   job-three:
